{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.\n",
      "\n",
      "1.15.3\n"
     ]
    }
   ],
   "source": [
    "import os, random, shutil\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import tensorflow as tf\n",
    "from glob import glob\n",
    "from PIL import Image \n",
    "\n",
    "print(tf.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'RANDOM_INIT' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-11-4706d491d2e2>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m tf.compat.v1.estimator.experimental.KMeans(\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mnum_clusters\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmodel_dir\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minitial_clusters\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mRANDOM_INIT\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m     \u001b[0mdistance_metric\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mSQUARED_EUCLIDEAN_DISTANCE\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mseed\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0muse_mini_batch\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mmini_batch_steps_per_iteration\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkmeans_plus_plus_num_retries\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mrelative_tolerance\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeature_columns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'RANDOM_INIT' is not defined"
     ]
    }
   ],
   "source": [
    "tf.compat.v1.estimator.experimental.KMeans(\n",
    "    num_clusters, model_dir=None, initial_clusters=RANDOM_INIT,\n",
    "    distance_metric=SQUARED_EUCLIDEAN_DISTANCE, seed=None, use_mini_batch=True,\n",
    "    mini_batch_steps_per_iteration=1, kmeans_plus_plus_num_retries=2,\n",
    "    relative_tolerance=None, config=None, feature_columns=None\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Using default config.\n",
      "WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpbmubm89c\n",
      "INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpbmubm89c', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8d61d07748>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "[[377.38910473 104.74534292]\n",
      " [579.02512306 912.07747595]\n",
      " [423.03040561 962.06251057]\n",
      " [128.94694852 620.43790778]\n",
      " [532.3783333  152.35488011]\n",
      " [992.3242847  917.13719476]\n",
      " [  6.07519354 413.15902586]\n",
      " [301.87975672 706.21852363]\n",
      " [ 45.27784618 554.78610491]\n",
      " [726.83172935 480.93007948]\n",
      " [537.61290353 859.60792881]\n",
      " [679.6115893   50.03210953]\n",
      " [621.10107908 983.28442707]\n",
      " [139.86676106 525.14636908]\n",
      " [353.00258105 432.92866547]\n",
      " [  5.65553526  78.48222212]\n",
      " [722.82235387 537.9327144 ]\n",
      " [816.50967187 865.77533527]\n",
      " [257.14246575 361.56516587]\n",
      " [630.23989884 436.60308638]\n",
      " [127.47609574 313.85997445]\n",
      " [583.99453411 612.63856323]\n",
      " [794.73541919 207.32924348]\n",
      " [752.66020448 390.06032547]\n",
      " [401.34068439 710.25007135]\n",
      " [435.52769184 810.05579382]\n",
      " [ 74.34329934 503.21884007]\n",
      " [588.27917795 924.31660156]\n",
      " [729.56295109  85.6184679 ]\n",
      " [944.94059993 619.35812432]\n",
      " [895.55172438 300.17385957]\n",
      " [234.24125431 347.23196823]\n",
      " [763.29410352 288.23433145]\n",
      " [582.6837511  483.92936337]\n",
      " [424.88108517 392.77129134]\n",
      " [713.91137441 269.77780365]\n",
      " [ 98.15591362 675.97247205]\n",
      " [196.19336517 973.46502488]\n",
      " [115.00698986 791.30292925]\n",
      " [367.46445415 837.3568206 ]\n",
      " [729.64100717 232.83547038]\n",
      " [514.1298612  611.70835665]\n",
      " [ 57.17580042 549.85989481]\n",
      " [927.68969109 358.66872521]\n",
      " [776.10031241 995.74440341]\n",
      " [994.29673381 405.06722203]\n",
      " [482.74306555 805.3263517 ]\n",
      " [661.53577266 835.34423056]\n",
      " [570.47223304 440.79139602]\n",
      " [402.29912847 543.05970598]\n",
      " [  3.6736767  280.55762685]\n",
      " [341.16868802 383.72801973]\n",
      " [301.74953404 917.86711118]\n",
      " [390.28102608 680.67326897]\n",
      " [697.69261536 848.98035294]\n",
      " [126.91408217 508.90852145]\n",
      " [159.98520567 736.09998859]\n",
      " [440.59619111 787.66078719]\n",
      " [807.1231165  861.35221419]\n",
      " [718.57811817 846.86172551]\n",
      " [990.84479611 329.57577137]\n",
      " [241.41426094 896.86513157]\n",
      " [745.69035768 881.54050944]\n",
      " [612.68992902 406.17470795]\n",
      " [500.37552389  44.80788781]\n",
      " [113.8496211  840.56276947]\n",
      " [288.7486818  927.63540178]\n",
      " [354.34477915 234.570413  ]\n",
      " [726.65065021 557.87213461]\n",
      " [658.76693412 904.43585354]\n",
      " [ 25.46957494 412.26254999]\n",
      " [653.25969267 373.97746599]\n",
      " [930.61476246 147.03829172]\n",
      " [ 21.7700031  686.03912362]\n",
      " [528.3414272  652.54549851]\n",
      " [504.12472581 152.95189823]\n",
      " [973.87810149 654.42477967]\n",
      " [112.6776524  198.07887237]\n",
      " [794.43736922 587.23771607]\n",
      " [ 18.78863099 607.07014225]\n",
      " [420.4258632  689.92315314]\n",
      " [  9.35040652  45.85773158]\n",
      " [426.46438771 101.10303881]\n",
      " [913.92499741 972.18701953]\n",
      " [259.93766142 441.93612957]\n",
      " [123.50467367 398.14772916]\n",
      " [764.35466078 208.69942269]\n",
      " [586.0364817  233.63992877]\n",
      " [857.31731242 822.8049702 ]\n",
      " [ 75.98292587 377.7106924 ]\n",
      " [146.61126171 658.33446514]\n",
      " [848.70027149 689.71252554]\n",
      " [190.21643345 389.31568288]\n",
      " [ 62.39513218 477.70829573]\n",
      " [434.52311936 103.10164934]\n",
      " [971.46314432 631.31716983]\n",
      " [343.8316994  690.31241865]\n",
      " [851.30160646 822.41930297]\n",
      " [ 32.31956987  74.7690687 ]\n",
      " [341.72551756  74.74697465]]\n"
     ]
    }
   ],
   "source": [
    "\n",
    "num_points = 100\n",
    "dimensions = 2\n",
    "points = np.random.uniform(0, 1000, [num_points, dimensions])\n",
    "\n",
    "def input_fn():\n",
    "  return tf.train.limit_epochs(\n",
    "      tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)\n",
    "\n",
    "num_clusters = 5\n",
    "kmeans = tf.estimator.experimental.KMeans(\n",
    "    num_clusters=num_clusters, use_mini_batch=False)\n",
    "\n",
    "print(points)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
      "WARNING:tensorflow:From <ipython-input-2-dd68b8a42a88>:7: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/input.py:112: RefVariable.count_up_to (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Prefer Dataset.range instead.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py:2522: count_up_to (from tensorflow.python.ops.state_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Prefer Dataset.range instead.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "WARNING:tensorflow:Training with estimator made no steps. Perhaps input is empty or misspecified.\n",
      "INFO:tensorflow:Loss for final step: None.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:26:59Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-1\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:26:59\n",
      "INFO:tensorflow:Saving dict for global step 1: global_step = 1, loss = 8108547.5, score = 8108547.5\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1: /tmp/tmpbmubm89c/model.ckpt-1\n",
      "score: 8108547.5\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-1\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py:1075: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file utilities to get mtimes.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 8108547.5, step = 2\n",
      "INFO:tensorflow:Saving checkpoints for 3 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 8108547.5.\n",
      "delta: [[-2.0677747e+02 -8.2117310e+01]\n",
      " [-4.5178894e+01 -7.0572266e+01]\n",
      " [-6.2589355e+01  1.7643555e+01]\n",
      " [-1.1608948e+02 -8.5274231e+01]\n",
      " [ 1.4073923e+02  1.3427734e-02]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:00Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-3\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:00\n",
      "INFO:tensorflow:Saving dict for global step 3: global_step = 3, loss = 5324053.0, score = 5324053.0\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 3: /tmp/tmpbmubm89c/model.ckpt-3\n",
      "score: 5324053.0\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-3\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 3 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 5324053.0, step = 3\n",
      "INFO:tensorflow:Saving checkpoints for 5 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 5324053.0.\n",
      "delta: [[-63.773804 -32.858948]\n",
      " [-54.615417 -75.64322 ]\n",
      " [ 17.447693  71.010864]\n",
      " [-24.478638 -45.204376]\n",
      " [-12.294876 -11.905273]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:00Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-5\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:01\n",
      "INFO:tensorflow:Saving dict for global step 5: global_step = 5, loss = 4695746.5, score = 4695746.5\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5: /tmp/tmpbmubm89c/model.ckpt-5\n",
      "score: 4695746.5\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-5\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 4695746.5, step = 6\n",
      "INFO:tensorflow:Saving checkpoints for 7 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 4695746.5.\n",
      "delta: [[-89.81659  -17.741394]\n",
      " [-34.803894 -46.488617]\n",
      " [-20.918701  34.15808 ]\n",
      " [-19.165405 -32.371567]\n",
      " [-18.472977 -32.465027]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:01Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-7\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:01\n",
      "INFO:tensorflow:Saving dict for global step 7: global_step = 7, loss = 4069427.8, score = 4069427.8\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 7: /tmp/tmpbmubm89c/model.ckpt-7\n",
      "score: 4069427.8\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-7\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 7 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 4069427.8, step = 7\n",
      "INFO:tensorflow:Saving checkpoints for 9 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py:969: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file APIs to delete files with this prefix.\n",
      "INFO:tensorflow:Loss for final step: 4069427.8.\n",
      "delta: [[-77.62366  -19.417236]\n",
      " [-15.53717  -36.99695 ]\n",
      " [-32.878357  33.9104  ]\n",
      " [-27.268433  -9.512238]\n",
      " [-24.900467 -43.731873]]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:02Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-9\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:02\n",
      "INFO:tensorflow:Saving dict for global step 9: global_step = 9, loss = 3644198.0, score = 3644198.0\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9: /tmp/tmpbmubm89c/model.ckpt-9\n",
      "score: 3644198.0\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-9\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 9 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 3644198.0, step = 10\n",
      "INFO:tensorflow:Saving checkpoints for 11 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 3644198.0.\n",
      "delta: [[-41.68921    -6.2108765]\n",
      " [-28.886902   -9.307495 ]\n",
      " [-23.829163    5.253357 ]\n",
      " [-19.6297    -24.243668 ]\n",
      " [ -5.1677322 -20.446259 ]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:02Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-11\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:03\n",
      "INFO:tensorflow:Saving dict for global step 11: global_step = 11, loss = 3427837.0, score = 3427837.0\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 11: /tmp/tmpbmubm89c/model.ckpt-11\n",
      "score: 3427837.0\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-11\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 11 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 3427837.0, step = 12\n",
      "INFO:tensorflow:Saving checkpoints for 13 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 3427837.0.\n",
      "delta: [[-43.09015  -19.326294]\n",
      " [-28.556824 -20.163239]\n",
      " [-23.869873   6.686096]\n",
      " [-55.07715  -49.25061 ]\n",
      " [-11.17585  -27.10025 ]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:03Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-13\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:03\n",
      "INFO:tensorflow:Saving dict for global step 13: global_step = 13, loss = 3228744.2, score = 3228744.2\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 13: /tmp/tmpbmubm89c/model.ckpt-13\n",
      "score: 3228744.2\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-13\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 3228744.2, step = 14\n",
      "INFO:tensorflow:Saving checkpoints for 15 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 3228744.2.\n",
      "delta: [[ -9.581177   -7.8654175]\n",
      " [  0.          0.       ]\n",
      " [-12.125916    9.42334  ]\n",
      " [  0.          0.       ]\n",
      " [  0.          0.       ]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:04Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-15\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:04\n",
      "INFO:tensorflow:Saving dict for global step 15: global_step = 15, loss = 3219247.0, score = 3219247.0\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 15: /tmp/tmpbmubm89c/model.ckpt-15\n",
      "score: 3219247.0\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-15\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 15 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 3219247.0, step = 16\n",
      "INFO:tensorflow:Saving checkpoints for 17 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 3219247.0.\n",
      "delta: [[ -8.987244   -5.9854736]\n",
      " [  0.          0.       ]\n",
      " [-12.601929    5.100281 ]\n",
      " [  0.          0.       ]\n",
      " [  0.          0.       ]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:04Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-17\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:05\n",
      "INFO:tensorflow:Saving dict for global step 17: global_step = 17, loss = 3208845.0, score = 3208845.0\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 17: /tmp/tmpbmubm89c/model.ckpt-17\n",
      "score: 3208845.0\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-17\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 17 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:loss = 3208845.0, step = 18\n",
      "INFO:tensorflow:Saving checkpoints for 19 into /tmp/tmpbmubm89c/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 3208845.0.\n",
      "delta: [[ -9.383606   -5.9733276]\n",
      " [  0.          0.       ]\n",
      " [-11.762512    3.9192505]\n",
      " [  0.          0.       ]\n",
      " [  0.          0.       ]]\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-12-14T14:27:05Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-19\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [1/1]\n",
      "INFO:tensorflow:Finished evaluation at 2020-12-14-14:27:05\n",
      "INFO:tensorflow:Saving dict for global step 19: global_step = 19, loss = 3203203.2, score = 3203203.2\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 19: /tmp/tmpbmubm89c/model.ckpt-19\n",
      "score: 3203203.2\n",
      "cluster centers: [[363.2021  774.69073]\n",
      " [763.88403 372.14542]\n",
      " [790.75    841.53   ]\n",
      " [490.95142 144.20364]\n",
      " [114.00517 419.15088]]\n"
     ]
    }
   ],
   "source": [
    "# train\n",
    "num_iterations = 10\n",
    "previous_centers = None\n",
    "for _ in range(num_iterations):\n",
    "    kmeans.train(input_fn)\n",
    "    cluster_centers = kmeans.cluster_centers()\n",
    "    if previous_centers is not None:\n",
    "        print('delta:', cluster_centers - previous_centers)\n",
    "    previous_centers = cluster_centers\n",
    "    print('score:', kmeans.score(input_fn))\n",
    "print('cluster centers:', cluster_centers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from /tmp/tmpbmubm89c/model.ckpt-19\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "point: [377.38910473 104.74534292] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [579.02512306 912.07747595] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [423.03040561 962.06251057] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [128.94694852 620.43790778] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [532.3783333  152.35488011] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [992.3242847  917.13719476] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [  6.07519354 413.15902586] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [301.87975672 706.21852363] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [ 45.27784618 554.78610491] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [726.83172935 480.93007948] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [537.61290353 859.60792881] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [679.6115893   50.03210953] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [621.10107908 983.28442707] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [139.86676106 525.14636908] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [353.00258105 432.92866547] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [ 5.65553526 78.48222212] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [722.82235387 537.9327144 ] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [816.50967187 865.77533527] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [257.14246575 361.56516587] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [630.23989884 436.60308638] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [127.47609574 313.85997445] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [583.99453411 612.63856323] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [794.73541919 207.32924348] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [752.66020448 390.06032547] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [401.34068439 710.25007135] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [435.52769184 810.05579382] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [ 74.34329934 503.21884007] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [588.27917795 924.31660156] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [729.56295109  85.6184679 ] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [944.94059993 619.35812432] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [895.55172438 300.17385957] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [234.24125431 347.23196823] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [763.29410352 288.23433145] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [582.6837511  483.92936337] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [424.88108517 392.77129134] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [713.91137441 269.77780365] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [ 98.15591362 675.97247205] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [196.19336517 973.46502488] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [115.00698986 791.30292925] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [367.46445415 837.3568206 ] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [729.64100717 232.83547038] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [514.1298612  611.70835665] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [ 57.17580042 549.85989481] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [927.68969109 358.66872521] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [776.10031241 995.74440341] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [994.29673381 405.06722203] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [482.74306555 805.3263517 ] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [661.53577266 835.34423056] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [570.47223304 440.79139602] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [402.29912847 543.05970598] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [  3.6736767  280.55762685] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [341.16868802 383.72801973] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [301.74953404 917.86711118] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [390.28102608 680.67326897] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [697.69261536 848.98035294] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [126.91408217 508.90852145] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [159.98520567 736.09998859] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [440.59619111 787.66078719] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [807.1231165  861.35221419] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [718.57811817 846.86172551] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [990.84479611 329.57577137] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [241.41426094 896.86513157] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [745.69035768 881.54050944] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [612.68992902 406.17470795] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [500.37552389  44.80788781] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [113.8496211  840.56276947] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [288.7486818  927.63540178] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [354.34477915 234.570413  ] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [726.65065021 557.87213461] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [658.76693412 904.43585354] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [ 25.46957494 412.26254999] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [653.25969267 373.97746599] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [930.61476246 147.03829172] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [ 21.7700031  686.03912362] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [528.3414272  652.54549851] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [504.12472581 152.95189823] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [973.87810149 654.42477967] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [112.6776524  198.07887237] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [794.43736922 587.23771607] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [ 18.78863099 607.07014225] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [420.4258632  689.92315314] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [ 9.35040652 45.85773158] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [426.46438771 101.10303881] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [913.92499741 972.18701953] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [259.93766142 441.93612957] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [123.50467367 398.14772916] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [764.35466078 208.69942269] is in cluster 1 centered at [763.88403 372.14542]\n",
      "point: [586.0364817  233.63992877] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [857.31731242 822.8049702 ] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [ 75.98292587 377.7106924 ] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [146.61126171 658.33446514] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [848.70027149 689.71252554] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [190.21643345 389.31568288] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [ 62.39513218 477.70829573] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [434.52311936 103.10164934] is in cluster 3 centered at [490.95142 144.20364]\n",
      "point: [971.46314432 631.31716983] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [343.8316994  690.31241865] is in cluster 0 centered at [363.2021  774.69073]\n",
      "point: [851.30160646 822.41930297] is in cluster 2 centered at [790.75 841.53]\n",
      "point: [32.31956987 74.7690687 ] is in cluster 4 centered at [114.00517 419.15088]\n",
      "point: [341.72551756  74.74697465] is in cluster 3 centered at [490.95142 144.20364]\n"
     ]
    }
   ],
   "source": [
    "# map the input points to their clusters\n",
    "cluster_indices = list(kmeans.predict_cluster_index(input_fn))\n",
    "for i, point in enumerate(points):\n",
    "    cluster_index = cluster_indices[i]\n",
    "    center = cluster_centers[cluster_index]\n",
    "    print('point:', point, 'is in cluster', cluster_index, 'centered at', center)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[363.2021 , 774.69073],\n",
       "       [763.88403, 372.14542],\n",
       "       [790.75   , 841.53   ],\n",
       "       [490.95142, 144.20364],\n",
       "       [114.00517, 419.15088]], dtype=float32)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "kmeans.cluster_centers()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'KMeansClustering' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-9-ddb9ed3e6622>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload_variable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkmeans\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodel_dir\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mKMeansClustering\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mCLUSTER_CENTERS_VAR_NAME\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'KMeansClustering' is not defined"
     ]
    }
   ],
   "source": [
    "tf.train.load_variable(kmeans.model_dir, KMeansClustering.CLUSTER_CENTERS_VAR_NAME)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'experimental_export_all_saved_models' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-4e4c1e20c8dc>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m experimental_export_all_saved_models(\n\u001b[0m\u001b[1;32m      2\u001b[0m     \u001b[0mexport_dir_base\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minput_receiver_fn_map\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0massets_extra\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mas_text\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m     \u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m )\n",
      "\u001b[0;31mNameError\u001b[0m: name 'experimental_export_all_saved_models' is not defined"
     ]
    }
   ],
   "source": [
    "experimental_export_all_saved_models(\n",
    "    export_dir_base, input_receiver_fn_map, assets_extra=None, as_text=False,\n",
    "    checkpoint_path=None\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "def serving():\n",
    "    inputs = {}\n",
    "   # for feat in df.columns:\n",
    "   #     inputs[feat] = tf.placeholder(shape=[None], dtype = tf.float32)\n",
    "    inputs = tf.placeholder(shape=[None,9], dtype = tf.float32)\n",
    "    return tf.estimator.export.TensorServingInputReceiver(inputs,inputs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['all_distances', 'cluster_index', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from ./data\n"
     ]
    },
    {
     "ename": "DataLossError",
     "evalue": "2 root error(s) found.\n  (0) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n\t [[save/RestoreV2/_1]]\n  (1) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n0 successful operations.\n0 derived errors ignored.\n\nOriginal stack trace for 'save/RestoreV2':\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n    app.start()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 583, in start\n    self.io_loop.start()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 153, in start\n    self.asyncio_loop.run_forever()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py\", line 442, in run_forever\n    self._run_once()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py\", line 1462, in _run_once\n    handle._run()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 787, in inner\n    self.run()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n    user_expressions, allow_stdin,\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n    return runner(coro)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-15-b3f50b3ad752>\", line 4, in <module>\n    experimental_mode=tf.estimator.ModeKeys.PREDICT)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 735, in export_saved_model\n    strip_default_attrs=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 859, in _export_all_saved_models\n    strip_default_attrs=strip_default_attrs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 959, in _add_meta_graph_for_mode\n    graph_saver = estimator_spec.scaffold.saver or saver.Saver(sharded=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 834, in __init__\n    self.build()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 846, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 884, in _build\n    build_restore=build_restore)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 508, in _build_internal\n    restore_sequentially, reshape)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 387, in _AddShardedRestoreOps\n    name=\"restore_shard\"))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 334, in _AddRestoreOps\n    restore_sequentially)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 581, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n    name=name)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n    op_def=op_def)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n    return func(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n    attrs, op_def, compute_device)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n    op_def=op_def)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n    self._traceback = tf_stack.extract_stack()\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDataLossError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1364\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1365\u001b[0;31m       \u001b[0;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1366\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[1;32m   1349\u001b[0m       return self._call_tf_sessionrun(options, feed_dict, fetch_list,\n\u001b[0;32m-> 1350\u001b[0;31m                                       target_list, run_metadata)\n\u001b[0m\u001b[1;32m   1351\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[0;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[1;32m   1442\u001b[0m                                             \u001b[0mfetch_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1443\u001b[0;31m                                             run_metadata)\n\u001b[0m\u001b[1;32m   1444\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mDataLossError\u001b[0m: 2 root error(s) found.\n  (0) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[{{node save/RestoreV2}}]]\n\t [[save/RestoreV2/_1]]\n  (1) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[{{node save/RestoreV2}}]]\n0 successful operations.\n0 derived errors ignored.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mDataLossError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-15-b3f50b3ad752>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      2\u001b[0m                           \u001b[0mserving_input_receiver_fn\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mserving\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m                           \u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'./data'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m                           experimental_mode=tf.estimator.ModeKeys.PREDICT)\n\u001b[0m",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\u001b[0m in \u001b[0;36mexport_saved_model\u001b[0;34m(self, export_dir_base, serving_input_receiver_fn, assets_extra, as_text, checkpoint_path, experimental_mode)\u001b[0m\n\u001b[1;32m    733\u001b[0m         \u001b[0mas_text\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mas_text\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    734\u001b[0m         \u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 735\u001b[0;31m         strip_default_attrs=True)\n\u001b[0m\u001b[1;32m    736\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    737\u001b[0m   def experimental_export_all_saved_models(\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\u001b[0m in \u001b[0;36m_export_all_saved_models\u001b[0;34m(self, export_dir_base, input_receiver_fn_map, assets_extra, as_text, checkpoint_path, strip_default_attrs)\u001b[0m\n\u001b[1;32m    857\u001b[0m             \u001b[0mbuilder\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minput_receiver_fn_map\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    858\u001b[0m             \u001b[0msave_variables\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmode\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mModeKeys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPREDICT\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 859\u001b[0;31m             strip_default_attrs=strip_default_attrs)\n\u001b[0m\u001b[1;32m    860\u001b[0m         \u001b[0msave_variables\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    861\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\u001b[0m in \u001b[0;36m_add_meta_graph_for_mode\u001b[0;34m(self, builder, input_receiver_fn_map, checkpoint_path, save_variables, mode, export_tags, check_variables, strip_default_attrs)\u001b[0m\n\u001b[1;32m    964\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mcheck_variables\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    965\u001b[0m           \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 966\u001b[0;31m             \u001b[0mgraph_saver\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrestore\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msession\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcheckpoint_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    967\u001b[0m           \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mNotFoundError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    968\u001b[0m             msg = ('Could not load all requested variables from checkpoint. '\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\u001b[0m in \u001b[0;36mrestore\u001b[0;34m(self, sess, save_path)\u001b[0m\n\u001b[1;32m   1294\u001b[0m       \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1295\u001b[0m         sess.run(self.saver_def.restore_op_name,\n\u001b[0;32m-> 1296\u001b[0;31m                  {self.saver_def.filename_tensor_name: save_path})\n\u001b[0m\u001b[1;32m   1297\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mNotFoundError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1298\u001b[0m       \u001b[0;31m# There are three common conditions that might cause this error:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m    954\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    955\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[0;32m--> 956\u001b[0;31m                          run_metadata_ptr)\n\u001b[0m\u001b[1;32m    957\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    958\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1178\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1179\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[0;32m-> 1180\u001b[0;31m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[1;32m   1181\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1182\u001b[0m       \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1357\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1358\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[0;32m-> 1359\u001b[0;31m                            run_metadata)\n\u001b[0m\u001b[1;32m   1360\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1361\u001b[0m       \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1382\u001b[0m                     \u001b[0;34m'\\nsession_config.graph_options.rewrite_options.'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1383\u001b[0m                     'disable_meta_optimizer = True')\n\u001b[0;32m-> 1384\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mop\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1385\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1386\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mDataLossError\u001b[0m: 2 root error(s) found.\n  (0) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n\t [[save/RestoreV2/_1]]\n  (1) Data loss: Unable to open table file ./data: Failed precondition: data; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]\n0 successful operations.\n0 derived errors ignored.\n\nOriginal stack trace for 'save/RestoreV2':\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n    app.start()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 583, in start\n    self.io_loop.start()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/platform/asyncio.py\", line 153, in start\n    self.asyncio_loop.run_forever()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py\", line 442, in run_forever\n    self._run_once()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/base_events.py\", line 1462, in _run_once\n    handle._run()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/asyncio/events.py\", line 145, in _run\n    self._callback(*self._args)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n    lambda f: self._run_callback(functools.partial(callback, future))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n    ret = callback()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 787, in inner\n    self.run()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 748, in run\n    yielded = self.gen.send(value)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n    yield gen.maybe_future(dispatch(*args))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n    yield gen.maybe_future(handler(stream, idents, msg))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n    user_expressions, allow_stdin,\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tornado/gen.py\", line 209, in wrapper\n    yielded = next(result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n    raw_cell, store_history, silent, shell_futures)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n    return runner(coro)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-15-b3f50b3ad752>\", line 4, in <module>\n    experimental_mode=tf.estimator.ModeKeys.PREDICT)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 735, in export_saved_model\n    strip_default_attrs=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 859, in _export_all_saved_models\n    strip_default_attrs=strip_default_attrs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 959, in _add_meta_graph_for_mode\n    graph_saver = estimator_spec.scaffold.saver or saver.Saver(sharded=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 834, in __init__\n    self.build()\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 846, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 884, in _build\n    build_restore=build_restore)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 508, in _build_internal\n    restore_sequentially, reshape)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 387, in _AddShardedRestoreOps\n    name=\"restore_shard\"))\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 334, in _AddRestoreOps\n    restore_sequentially)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py\", line 581, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py\", line 1696, in restore_v2\n    name=name)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py\", line 794, in _apply_op_helper\n    op_def=op_def)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py\", line 507, in new_func\n    return func(*args, **kwargs)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 3357, in create_op\n    attrs, op_def, compute_device)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 3426, in _create_op_internal\n    op_def=op_def)\n  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py\", line 1748, in __init__\n    self._traceback = tf_stack.extract_stack()\n"
     ]
    }
   ],
   "source": [
    "kmeans.export_saved_model(\"./data\", \n",
    "                          serving_input_receiver_fn=serving,\n",
    "                          checkpoint_path='./data',\n",
    "                          experimental_mode=tf.estimator.ModeKeys.PREDICT)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:tensorflow_p36]",
   "language": "python",
   "name": "conda-env-tensorflow_p36-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
